### ISSUE TITLE
I don't understand how overridables work

### ISSUE THREAD

**Issue by 39555** [metent/uair#26]
Hi! Im trying to integrate `uair` with `yambar` and I want to use `listen` with a specific `format` option. There are no examples of the config with the overridables property, and I can't figure out how it is supposed to work

**Comment by metent** [comment]
Hi! So, this isn't documented well as it *was* subject to change as I was dissatisfied with the current IPC architecture and the verbose configuration, but then I went on hiatus (see my other comment in issue #21). For now, you can assume that overridables are not being deprecated anytime soon. Here's an example to show how overridables work:

Let's say you have this config file:

```toml
[defaults]
format = "{time}\n"

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
command = "notify-send 'Rest Done!'"
```

If you use `uairctl listen`, the formatting will be done according to the same config file, as `uairctl` acts like a 'client' process here. If you need to specify a different format, while still keeping the timers synchronized with each other, you can use overrides to specify additional naming schemes in the config file.
We can add overrides like this:

```toml
[defaults]
format = "{time}\n"
overrides = { custom_key1 = { format = "Time: {time}\n", time_format = "%H:%M:%S" }, custom_key2 = { .. } }

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
command = "notify-send 'Rest Done!'"
```

Now, if I run `uair` and then run `uairctl listen -o custom_key1`,  you would see that the `uairctl` command would output/pipe/redirect according to the `format` and `time_format` properties specified inside `defaults.overrides.custom_key1`. The properties which are not specified inside the overridables table are not overriden and are inherited from the main config. You can also specify the `overrides` key per session, if more specific configuration is needed.
